baseURL = "http://positive-pets.co.uk/"
languageCode = "en-us"
title = "Positive-Pets Dog Training"
theme = "strata"
publishDir = "docs"

[params]
  # Metadata for search engines and social sharing
  author = "Emma Pimm"

  favicon = "images/favicon.png"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/dog.jpg"
      position = "center center"


  [params.sidebar]
    avatar = "avatar.jpg"
    bio = "<br><br><br><br><br><br><br><br>**Positive-Pets** Dog training based in Didcot"
    twitter = ""
    github = ""
    gitlab = ""
    dribbble = ""
    facebook = ""
    googleplus = ""
    flickr = ""
    linkedin = ""

    copyright = [
      "&copy; Emma Pimm",
      "Design: [HTML5 UP](//html5up.net)"
    ]

  [params.about]
    hide  = false
    title = "Dog training based in Didcot. Helping your dog to reach full potential using kind, effective and up-to-date methods."
    content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


  [params.contact]
    hide  = true